# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} > access_token.txt
          go run MdRepoGenerator.go
          rm -rf access_token.txt
      - name: update the list
        env:
          GITHUB_USER: "qdriven"
        run: |
          git config user.name "${GITHUB_USER}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout main
          git commit -am "scheduled: auto update"
          git push -u origin main
#jobs:
#
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.18
#
#    - name: Build
#      run: go build -v ./...
#
#    - name: Test
#      run: go test -v ./...
